### ISSUE TITLE
Should add a subsection in the hoon document about `fuse-loop`

### ISSUE THREAD

**Issue by ynx0** [ashelkovnykov/urbit-faq#1]
My general heuristic is that it has something to do with list types being off somehow, but a proper understanding would help.

**Comment by ashelkovnykov** [comment]
Should be addressed by [this commit](https://github.com/ashelkovnykov/urbit-faq/commit/b4a41b1b0b23c560d23b5fed7be9c4f7d3077b15).

**Comment by ynx0** [comment]
Thanks!
